export const START_LOADING = "START_LOADING"; 
export const END_LOADING = "END_LOADING";
export const GET_QUOTE = "GET_QUOTE";
export const BOOKMARK_THE_QUOTE = "BOOKMARK_THE_QUOTE";
export const GET_QUOTE_BY_TAGS = "GET_QUOTE_BY_TAGS";
export const REMOVE_THE_BOOKMARK = "REMOVE_THE_BOOKMARK";
